repos:
  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-added-large-files
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      - id: detect-aws-credentials
        stages: [commit]
        args:
          - --allow-missing-credentials
  - repo: git@github.com:kadrach/pre-commit-gitlabci-lint
    rev: ab984c60414b012e294a65166691473047ccce49
    hooks:
      - id: gitlabci-lint
        stages: [commit]
  - repo: git@github.com:coyainsurance/pre-commit-scalafmt.git
    rev: 966904e193ea7579fcaeef3b2cb64fe6ab76db46
    hooks:
      - id: scalafmt
        stages: [commit]
        args: [-c .scalafmt.conf, -d./bin, -v1.5.1]
