language: scala
dist: trusty # If unspecified uses Xenial images, which no longer support oraclejdk8
sudo: false

matrix:
  include:
    - jdk: oraclejdk8
    - scala: 2.12.4

  script:
    - sbt test

