language: scala
dist: trusty # If unspecified uses Xenial images, which no longer support oraclejdk8
sudo: false

jdk: openjdk8

matrix:
  include:
    - scala: 2.12.13
    - scala: 2.13.5

  script:
    - sbt scapegoat test

